
server:
  port: 8889

#spring:
#  jackson:
#    date-format: yyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  datasource:
#    url: jdbc:mysql://localhost:3306/wx-video?serverTimezone=GMT%2B8&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#mybatis:
#  mapper-locations: classpath:/mapper/*.xml
#
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

